name: MrJobs.WebJob.DotNet Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment:
      name: Production
    env:
      ZIP_PATH: "./output"
      ZIP_FILE: "mrjobs.zip"
      ZIP_FILEPATH: "./output/mrjobs.zip"
      BINARIES: "./output/App_Data/jobs/continuous/mrjobs"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install .NET runtime
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.BUILD_DOTNET_VERSION }}
      - name: Run .NET commands
        shell: pwsh
        run: |
          dotnet restore "${{ vars.WEB_JOB_PROJECT_PATH }}"
          dotnet publish "${{ vars.WEB_JOB_PROJECT_PATH }}" --configuration Release --output "${{env.BINARIES}}"
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: webjob-artifact
      #     path: ${{env.BINARIES}}
      - name: Replace appsettings.json tokens
        uses: cschleiden/replace-tokens@v1.3
        with:
          tokenPrefix: "{{"
          tokenSuffix: "}}"
          files: ./appsettings.json
        env:
          WEB_API_HOST: ${{ vars.WEB_API_HOST }}
          WEB_API_SCOPE: ${{ secrets.WEB_API_SCOPE }}
      - name: Zip
        shell: pwsh
        run: |
          Compress-Archive -Path '${{ env.ZIP_PATH }}/*' -DestinationPath '${{ env.ZIP_FILEPATH }}' -Force
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A7C976CED4E3453387EF337A2411A2AC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_85BF8C9AC6694FBB8F13927E9D5FF53B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_63D7095076824EE5B858CCAD6E737B8F }}
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP }}
          package: ${{ env.ZIP_FILEPATH }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      - name: Logout of Azure
        run: |
          az logout
